### ISSUE TITLE
How can I mount directory to node containers ?

### ISSUE THREAD

**Issue by skeenerok** [aandryashin/selenoid#23]
Hi,
I have several tests with upload and download files. Usually, I mount directories with required files to the container with browser but it this case I did not find the way how to configure selenoid to start containers and mount directories to them. Also, It is nice to know how to set dns and dns-search for containers which were started by selenoid.

**Comment by skeenerok** [comment]
Example:

**Comment by skeenerok** [comment]
Example my current start command:
> docker run -d -P --dns=192.168.64.1 --dns-search=intra --dns-search=example.com  -e 'SCREEN_WIDTH=1220' -e 'SCREEN_HEIGHT=1000' -e DISPLAY=:99.0 -p 5903:5900 --link selenium-hub:hub -v /home/user/Downloads/:/home/seluser/Downloads/ -v /home/user/webdriver/uploads:/uploads selenium/node-firefox-debug:2.53.1

As a result, to check whether files are downloaded I use '/home/user/Downloads' path on the host, to specify the upload path in the browser - '/uploads/$file' of container file system.

**Comment by vania-pooh** [comment]
@skeenerok Selenium protocol allows to upload files using profiles. Regarding downloading files - how about downloading them using direct link? According to what I know - that's not a trivial task to download file because file dialog is native in each browser.

**Comment by aandryashin** [comment]
@skeenerok We did not plan to implement all docker client functionality in selenoid. In distributed environment users do not have access to individual seleniun nodes and cannot mount local filesystems. To download files or capture and manipulate traffic you can use this tool https://github.com/lightbody/browsermob-proxy.

**Comment by vania-pooh** [comment]
@skeenerok closing this question as answer was provided. Feel free to reopen if you have more questions.
