### ISSUE TITLE
Pull specific browser version

### ISSUE THREAD

**Issue by evanburrows** [aandryashin/selenoid#28]
Is there any way to pull a specific browser version for chrome or firefox?  Or would that require updating the dockerfiles and maintaining my own images on dockerhub?  When I tried the following it failed:

$ docker pull selenoid/firefox:48.0
Error response from daemon: manifest for selenoid/firefox:48.0 not found

I tried to find a gitter or slack channel for your work but didn't see anything.  Is issues the best way to ask questions.  I have a lot of interest in using this for some of my scenarios but I can't seem to get my chimp.js or webdriverio configurations correct.  I can see the selenoid browser spinning up but it fails with the following error:

[22:35:29]  COMMAND	POST 	 "/wd/hub/session"
[22:35:29]  DATA		{"desiredCapabilities":{"javascriptEnabled":true,"locationContextEnabled":true,"handlesAlerts":true,"rotatable":true,"maxInstances":1,"browserName":"firefox","loggingPrefs":{"browser":"ALL","driver":"ALL"},"requestOrigins":{"url":"http://webdriver.io","version":"4.6.2","name":"webdriverio"}}}
ERROR: [object Object]
firefox
Error

I have been struggling with this for a few days and decided it was time to break down and ask the experts.

/r

**Comment by vania-pooh** [comment]
@evanburrows currently browsers choice is rather poor but we would like to build a collection of images for Selenoid during next weeks. So please don't waste your time creating images yourself - that's our duty. For the moment the project is not so mature but we'll apply all possible effort to deliver the best product possible. Btw, is it ok for you to use [Telegram](https://telegram.org/) to ask questions?

**Comment by evanburrows** [comment]
@vania-pooh Thanks.  I am not so hung up on the current browser versions.  I am sure that will come with time.  If I could resolve the connectivity from either webdriverio or chimp.js.  Right now though I get a similar error as show above when I pass chrome or firefox as part of my DesiredCapabilities.  Is there additional information that I could provide to get the connectivity issue resolved?  

This is currently what I am seeing and it if it is helpful at all for debugging:

bash-3.2$ chimp
(node:8350) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
Feature: Search the Web

    As a human
    I want to search the web
    So I can find information

  @watch
  Scenario: Search for xolv.io
  ✔ Given I have visited Google
  ✔ When I search for "xolv.io"
{ ELEMENT: '0.8761588111607701-3',
  selector: 'a',
  value: { ELEMENT: '0.8761588111607701-3' },
  index: 1 }
  ✔ Then I see "xolv.io"

1 scenario (1 passed)
3 steps (3 passed)
0m01.688s
bash-3.2$ chimp --host 127.0.0.1 --port 4444 --browser firefox

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
(node:8363) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[chimp][helper] setupBrowserAndDDP had error
TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:190:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:467:23)
    at initBrowser (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at /usr/local/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /usr/local/lib/node_modules/chimp/node_modules/cucumber/node_modules/meteor-promise/fiber_pool.js:32:39
TypeError: Cannot read property 'trim' of undefined
    at sanitizeErrorMessage (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:190:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/chimp/node_modules/wdio-sync/build/index.js:467:23)
    at initBrowser (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (/usr/local/lib/node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at /usr/local/lib/node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at /usr/local/lib/node_modules/chimp/node_modules/cucumber/node_modules/meteor-promise/fiber_pool.js:32:39
Cucumber steps failed
bash-3.2$

Thanks!!

**Comment by vania-pooh** [comment]
@evanburrows unfortunately we're not using Javascript. So the best thing you can do to fix this - is to provide a small example. E.g. a tiny project in your Github with one test, so we could just type:
```
$ chimp
```
...and tcpdump what's going on there. Could you do this?

**Comment by evanburrows** [comment]
Here you go https://github.com/evanburrows/chimp-acceptance-example

just clone it and run "npm install" (assuming you have node already installed
there are npm commands to run against the browsers
npm run chrome
npm run firefox
and npm run phantomjs

Phantomjs works locally like it should, chrome works against selenoid, but firefox does not

**Comment by evanburrows** [comment]
by the way.  Chrome and firefox work fine with the code against a locally managed selenium install.  My selenium firefox node is running geckodriver as well.

**Comment by evanburrows** [comment]
wait, actually hold off on the firefox piece working.  It is looking a bit wonky.  Let me take a look at that piece again and i may need to submit an issue with the chimp folks

**Comment by vania-pooh** [comment]
@evanburrows any updates?

**Comment by vania-pooh** [comment]
@evanburrows created images for all FF versions starting from 3.6. See https://hub.docker.com/r/selenoid/firefox/tags/.

**Comment by evanburrows** [comment]
Thanks.  I reworked this into my code and updated a few things on my end (pulled the browser docker images, etc.).  Below is my browser config:

```
{
  "firefox": {
    "default": "latest",
    "versions": {
      "48.0": {
        "image": "selenoid/firefox:48.0",
        "port": "4444"
      },
      "latest": {
        "image": "selenoid/firefox:latest",
        "port": "4444"
      }
    }
  },
  "chrome": {
    "default": "latest",
    "versions": {
      "48.0": {
        "image": "selenoid/chrome:48.0",
        "port": "4444"
      },
      "latest": {
        "image": "selenoid/chrome:latest",
        "port": "4444"
      }
    }
  }
}
```

Start up the selenoid node using: `$ docker run -d --name selenoid -p 4444:4444 -v /Users/eburrows/devel/docker/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock selenoid/hub`

The call now works for chimp but does not reference the specified version.  It only launches chrome:latest.  
`$ node_modules/.bin/chimp --host 127.0.0.1 --port 4444 --path=tests --browser=chrome --browser-version=48.0`

However, I don't know if selenoid is properly doing the browser version handling since it always launches chrome:latest.  That handling is planned to be implemented in 1.2.0, correct?  What does your current implementation schedule look like?

**Comment by evanburrows** [comment]
Firefox is still broken though when connecting to selenoid.  I am having some conversations with the chimp maintainers on that.

```
$ node_modules/.bin/chimp --host 127.0.0.1 --port 4444 --path=tests --browser=firefox

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: [object Object]]
  message:
   { status: undefined,
     type: 'unknown',
     message: 'unknown',
     orgStatusMessage: undefined },
  type: 'RuntimeError' }
Error: [object Object]
    at initBrowser (node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at node_modules/meteor-promise/fiber_pool.js:32:39
Cucumber steps failed
```

**Comment by evanburrows** [comment]
One more update.  I changes the firefox:latest definition in browsers.json to reference firefox:47.0 and then firefox:48.0.  With 48.0 I am least get a different error response

```
$ node_modules/.bin/chimp --host 127.0.0.1 --port 4444 --path=tests --browser=firefox --browser-version=48.0

Master Chimp and become a testing Ninja! Check out our course: http://bit.ly/2btQaFu


[chimp] Running...
[chimp][helper] setupBrowserAndDDP had error
{ [Error: <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
  <script type="text/javascript">
    var json = Object.freeze('{"version":"3.2.0","type":"Standalone","consoleLink":"/wd/hub"}')]
  message: '<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>\n  <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />\n  <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>\n  <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>\n  <script type="text/javascript">\n    var json = Object.freeze(\'{"version":"3.2.0","type":"Standalone","consoleLink":"/wd/hub"}\')',
  type: 'RuntimeError' }
Error: <!DOCTYPE html>
    at initBrowser (node_modules/chimp/dist/lib/chimp-helper.js:174:17)
    at Object.setupBrowserAndDDP (node_modules/chimp/dist/lib/chimp-helper.js:248:7)
    at node_modules/chimp/dist/lib/cucumberjs/hooks.js:21:24
    at node_modules/meteor-promise/fiber_pool.js:32:39
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="/assets/displayhelpservlet.css" media="all"/>
    <link href="/assets/favicon.ico" rel="icon" type="image/x-icon" />
    <script src="/assets/jquery-3.1.1.min.js" type="text/javascript"></script>
    <script src="/assets/displayhelpservlet.js" type="text/javascript"></script>
    <script type="text/javascript">
    var json = Object.freeze('{"version":"3.2.0","type":"Standalone","consoleLink":"/wd/hub"}')
Cucumber steps failed
```
I will reach out to the chimp.js folks and try to figure out what may be going on that side of things

**Comment by aandryashin** [comment]
Please try to run aandryashin/selenoid image instead of selenoid/hub.

**Comment by vania-pooh** [comment]
@evanburrows 
1) This is not obvious but for Firefox images you need to have the following config:
```
"48.0": {
        "image": "selenoid/firefox:48.0",
        "port": "4444",
        "path": "/wd/hub"
      },
```
This is because Firefox containers have Selenium server inside which creates new session on ```/wd/hub```.
2) Please check that ```version``` capability is passed to Selenoid by Chimp. Not sure how it should be done. It seems you are not passing any version and thus Selenoid uses default version - ```latest```.

**Comment by evanburrows** [comment]
Alright I think I may be good now.  The docker hub image didn't make a difference but after adding the options to the config as suggested by @vania-pooh and changing the parameters a bit things look to be better. It is passing the correct parameters.  I am still having a few issues but they are on the chimp/selenium side rather than the selenoid.  I think this should be good to close now.  Thank you for all the help.
