### ISSUE TITLE
Use server timezone in containers

### ISSUE THREAD

**Issue by vania-pooh** [aandryashin/selenoid#30]
Need to set containers TZ variable equal to server's one.

**Comment by vania-pooh** [comment]
E.g. ```--env "TZ=Europe/Moscow"```.

**Comment by leonsabr** [comment]
In Kotlin & docker-java I use: `.withEnv("TZ=${ZoneId.systemDefault()}")`

**Comment by aandryashin** [comment]
Fixed in 9db44bde4096f1e5077e4ae6f8bc0254a0b94629. When running Selenoid within container add TZ environment variable. Please check.
