### ISSUE TITLE
Unable to create internal browser container

### ISSUE THREAD

**Issue by sskorol** [aandryashin/selenoid#32]
Hi @aandryashin @vania-pooh,

On MacOS I've faced with an issue that `selenoid` container can't internally raise `chrome` container.

Here's how I start a root container:

```sh
docker run -d --name selenoid-1 -p 4444:4444 -v /etc/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aandryashin/selenoid:latest
```

Here are container's logs:
```sh
2017/03/27 08:57:31 Loading configuration files...
2017/03/27 08:57:31 Loaded configuration from [/etc/selenoid/browsers.json]
2017/03/27 08:57:31 Using default containers log configuration because of: read error: open config/container-logs.json: no such file or directory
2017/03/27 08:57:31 Timezone: Local
2017/03/27 08:57:31 Listening on :4444
2017/03/27 08:58:20 [NEW_REQUEST]
2017/03/27 08:58:20 [NEW_REQUEST_ACCEPTED]
2017/03/27 08:58:20 Locating the service for chrome latest
2017/03/27 08:58:20 Using docker service for chrome latest
2017/03/27 08:58:20 Creating Docker container selenoid/chrome:latest ...
2017/03/27 08:58:21 Starting container...
2017/03/27 08:58:21 Container 0fe4e8516085455e922a2eb74fd03248e8206c9f124af073d4157310e31f490a started
Removing container 0fe4e8516085455e922a2eb74fd03248e8206c9f124af073d4157310e31f490a
Container 0fe4e8516085455e922a2eb74fd03248e8206c9f124af073d4157310e31f490a removed
2017/03/27 08:58:32 [SERVICE_STARTUP_FAILED] [error: http://172.17.0.1:32774 does not respond in 10s]
```

The most interesting thing is that it has worked well for some fixed period of time. But now it doesn't.

Any ideas about the root cause?

**Comment by vania-pooh** [comment]
@sskorol  could you try with release container: ```aandryashin/selenoid:1.0.0```.

**Comment by sskorol** [comment]
@vania-pooh just to clarify: what do you mean by releasing? As I've tried stop / rm / rmi commands + additional volume cleanup images. No luck.

**Comment by vania-pooh** [comment]
@sskorol I mean you should use tagged Selenoid container image (i.e. ```1.0.0```) instead of latest. Container with ```latest``` tag is the HEAD of the trunk. Although we test before closing issue it can certainly be unstable.

**Comment by sskorol** [comment]
@vania-pooh just tried with 1.0.0, no luck. Had also reset docker itself and pulled images from scratch -> similar result.

Probably the same issue: http://automated-testing.info/t/ne-iniczializiruetsya-remotewebdriver-esli-v-roli-grid-vystupaet-selenoid/12991

**Comment by aandryashin** [comment]
Unfortunately, I could not reproduce the issue. I have increased hardcoded limit for waiting while service started up to 30 sec. Please try with the images tagged as latest see if it helps.

**Comment by aandryashin** [comment]
Also, please try to run selenoid/chrome:latest container using docker and see output.

**Comment by aandryashin** [comment]
Another way to see logs is using docker logs on container started by selenoid while it running, I hope 30 sec is enough.

**Comment by vania-pooh** [comment]
@sskorol did the recommendations above help?

**Comment by sskorol** [comment]
@vania-pooh @aandryashin from provided above post author just opened additional ports range (those which are used for internal chrome / firefox containers creation) on docker host, and it fixed an issue. I'm gonna try the same tomorrow and let you know.

**Comment by sskorol** [comment]
@vania-pooh @aandryashin seems like the issue is now resolved for me. And the root cause was in wrong `browsers.json` vs `username.xml` host address / ports configuration.

Would be great to provide some explanations in docs what does `port` / `host` parameters stand for in both user guides, as it appears a bit confusing while trying to move away from default configuration.

Thanks for your time.

**Comment by vania-pooh** [comment]
@sskorol got it. Will add more details in docs soon. Thank you for the feedback.
