### ISSUE TITLE
Selenoid status returns unknown username while proxying via ggr

### ISSUE THREAD

**Issue by sskorol** [aandryashin/selenoid#37]
@vania-pooh @aandryashin hi,

Just curious how we could force Selenoid displaying real username we used for authorization via ggr?

![image](https://cloud.githubusercontent.com/assets/6638780/24580258/9e87cc64-170d-11e7-8f86-60c248e7e0f7.png)

I have added `users.htpasswd` and used valid credentials in connection URL:

```
http://skorol:password@localhost:4444/wd/hub
```

However, selenoid status request always returns `unknown`. Any idea about the root cause?

Here's the log from ggr container:

![image](https://cloud.githubusercontent.com/assets/6638780/24580316/bcda3372-170e-11e7-80b0-feeef9ea0074.png)

**Comment by vania-pooh** [comment]
@sskorol we use the same basic authentication headers to get user name. Let's check whether ggr actually proxies these headers to selenoid.

**Comment by vania-pooh** [comment]
Created https://github.com/aandryashin/ggr/issues/45.

**Comment by vania-pooh** [comment]
@sskorol we fixed this in latest GGR source. Please pull ```aandryashin/ggr:latest``` and check whether the issue is now fixed.

**Comment by sskorol** [comment]
@vania-pooh @aandryashin fixed in latest version, thanks!

![image](https://cloud.githubusercontent.com/assets/6638780/24588511/6455398a-17d2-11e7-8684-c9f041680a74.png)
