### ISSUE TITLE
Starting IEdriver does not work

### ISSUE THREAD

**Issue by vania-pooh** [aandryashin/selenoid#8]
This is my browsers.json:
```
admin@selenium-pc ~
$ cat ./browsers.json
{
  "internet explorer": {
    "default": "10",
    "versions": {
      "10": {
        "image": ["C:\\cygwin\\lib\\selenium\\iedriver.exe", "--log-level=DEBUG"]
      }
    }
  }
}
```

Here are Selenoid logs:
```
admin@selenium-pc ~
$ ./selenoid.exe -conf ./browsers.json -disable-docker
2016/11/15 14:49:03 Listening on :4444
2016/11/15 14:55:36 [NEW_REQUEST]
2016/11/15 14:55:36 [NEW_REQUEST_ACCEPTED]
2016/11/15 14:55:36 Locating the service for internet explorer 10
2016/11/15 14:55:36 Using driver service for internet explorer 10
2016/11/15 14:55:36 Trying to allocate port
2016/11/15 14:55:36 Available port is: 62884
2016/11/15 14:55:36 Starting process: [C:\cygwin\lib\selenium\iedriver.exe --log-level=DEBUG --port=62884]
2016/11/15 14:55:36 Process 3728 started in: 52.7343ms
2016/11/15 14:55:36 Proxying requests to: http://127.0.0.1:62884
2016/11/15 14:55:36 [SESSION_ATTEMPTED] [http://127.0.0.1:62884] <==== Freezes at this line!
```
But the process gets created and works:
```
admin@selenium-pc ~
$ curl -s -I http://127.0.0.1:62884
HTTP/1.1 200 OK
Content-Length: 136
Content-Type: text/html; charset=UTF-8
Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept
Accept-Ranges: bytes
Connection: close


admin@selenium-pc ~
$ ps -W | grep iedriver
     3728       0       0       3728  ?          0 15:55:37 C:\cygwin\lib\selenium\iedriver.exe
```
I think there's either an issue with blocking on channels or some Windows proxying particularity.

**Comment by vania-pooh** [comment]
Seems to freeze on this line: https://github.com/aandryashin/selenoid/blob/master/selenoid.go#L104 because default http client has no timeout specified.

**Comment by vania-pooh** [comment]
Hmmm...
```
2016/11/15 16:11:44 Listening on :4444
2016/11/15 16:13:03 [NEW_REQUEST]
2016/11/15 16:13:03 [NEW_REQUEST_ACCEPTED]
2016/11/15 16:13:03 Locating the service for internet explorer 10
2016/11/15 16:13:03 Using driver service for internet explorer 10
2016/11/15 16:13:03 Trying to allocate port
2016/11/15 16:13:03 Available port is: 50677
2016/11/15 16:13:03 Starting process: [C:\cygwin\lib\selenium\iedriver.exe --log-level=DEBUG --logfile=C:\cygwin\lib\selenium\iedriver_auto.log --port=50677]
2016/11/15 16:13:04 Process 2608 started in: 78.125ms
2016/11/15 16:13:04 Proxying requests to: http://127.0.0.1:50677
2016/11/15 16:13:04 [SESSION_ATTEMPTED] [http://127.0.0.1:50677]
2016/11/15 16:50:02 [SESSION_FAILED] [http://127.0.0.1:50677] - [Post http://127.0.0.1:50677/session: read tcp 127.0.0.1:50681->127.0.0.1:50677: wsarecv: An existing connection was forcibly closed by the remote host.]
2016/11/15 16:50:02 Terminating process 2608
2016/11/15 16:50:02 Cannot terminate process 2608: TerminateProcess: Access is denied.
```
Seems to be permissions-related issue.

**Comment by aandryashin** [comment]
There is an error when launching IE related to enabling protected mode, please check this settings.

**Comment by aandryashin** [comment]
PS C:\Users\Administrator> curl -Method Post -Body '{"desiredCapabilities":{"browserName":"internet explorer"}}' http://
localhost:4444/session
curl : {"sessionId":"70333849-12c9-4acf-9a35-480b878a3ad3","status":6,"value":{"message":"Unexpected error launching
Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the
same value (enabled or disabled) for all zones."}}

**Comment by aandryashin** [comment]
Appropriated registry key value should be set.

**Comment by aandryashin** [comment]
Here is full session.

client:
PS C:\Users\Administrator> curl -Method Post -Body '{"desiredCapabilities":{"browserName":"internet explorer"}}' http://
localhost:4444/wd/hub/session
curl : {"sessionId":"0c4951d6-23d4-4aa0-8193-9ba9e92fe19c","status":6,"value":{"message":"Unexpected error launching
Internet Explorer. Protected Mode settings are not the same for all zones. Enable Protected Mode must be set to the
same value (enabled or disabled) for all zones."}}

server:
2016/11/15 21:37:16 Listening on :4444
2016/11/15 21:37:39 [NEW_REQUEST]
2016/11/15 21:37:39 [NEW_REQUEST_ACCEPTED]
2016/11/15 21:37:39 Locating the service for internet explorer
2016/11/15 21:37:39 Using default version: latest
2016/11/15 21:37:39 Using driver service for internet explorer latest
2016/11/15 21:37:39 Trying to allocate port
2016/11/15 21:37:39 Available port is: 49756
2016/11/15 21:37:39 Starting process: [IEDriverServer --port=49756]
2016/11/15 21:37:39 Process 2392 started in: 56.9992ms
2016/11/15 21:37:39 Proxying requests to: http://127.0.0.1:49756
2016/11/15 21:37:39 [SESSION_ATTEMPTED] [http://127.0.0.1:49756]
2016/11/15 21:37:39 [SESSION_CREATED] [0c4951d6-23d4-4aa0-8193-9ba9e92fe19c] [http://127.0.0.1:49756]
2016/11/15 21:38:39 [SESSION_TIMED_OUT] [0c4951d6-23d4-4aa0-8193-9ba9e92fe19c] - Deleting session
2016/11/15 21:38:39 [DELETE_FAILED]
2016/11/15 21:38:39 Terminating process 2392
2016/11/15 21:38:39 Process 2392 terminated
2016/11/15 21:38:39 [FORCED_SESSION_REMOVAL] [0c4951d6-23d4-4aa0-8193-9ba9e92fe19c]

**Comment by aandryashin** [comment]
System: Windows 7 64bit
Driver: http://selenium-release.storage.googleapis.com/3.0/IEDriverServer_x64_3.0.0.zip
selenoid runs as administrator.

**Comment by vania-pooh** [comment]
Will check this. However I'm 100% sure that Protected Mode Settings are OK.

**Comment by vania-pooh** [comment]
To be tested.

**Comment by vania-pooh** [comment]
Works. Closing.
